workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.tradingsignals.app"
      node: 18.17.0
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Set Gradle version to 8.3
        script: |
          cd android
          sed -i '' 's|gradle-.*-all.zip|gradle-8.3-all.zip|g' gradle/wrapper/gradle-wrapper.properties || \
          sed -i 's|gradle-.*-all.zip|gradle-8.3-all.zip|g' gradle/wrapper/gradle-wrapper.properties
      - name: Make gradlew executable
        script: |
          chmod +x android/gradlew
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleDebug --no-daemon
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - ivannavi.code@gmail.com
        notify:
          success: true
          failure: true
